
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `SpeakRDb`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=SpeakR;Integrated Security=SSPI;`
//     Schema:                 ``
//     Include Views:          `False`

using System;

namespace Data.Core.Models
{
    public class Talk
    {
        public long Id { get; set; }
        public long PresentationId { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool IsStarted { get; set; }
    }
}
