using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("0.0.0.*")]
[assembly: AssemblyFileVersionAttribute("0.0.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright 2016")]
[assembly: AssemblyProductAttribute("SpeakR")]
[assembly: AssemblyCompanyAttribute("Headspring Labs")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0.*")]
