
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `SpeakRDb`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=SpeakR;Integrated Security=SSPI;`
//     Schema:                 ``
//     Include Views:          `False`

using System;

namespace Models
{
    
    public partial class Version 
    {
		public long id { get; set; }
		public string repository_path { get; set; }
		public string version { get; set; }
		public DateTime? entry_date { get; set; }
		public DateTime? modified_date { get; set; }
		public string entered_by { get; set; }
	}
    
    public partial class ScriptsRun 
    {
		public long id { get; set; }
		public long? version_id { get; set; }
		public string script_name { get; set; }
		public string text_of_script { get; set; }
		public string text_hash { get; set; }
		public bool? one_time_script { get; set; }
		public DateTime? entry_date { get; set; }
		public DateTime? modified_date { get; set; }
		public string entered_by { get; set; }
	}
    
    public partial class ScriptsRunError 
    {
		public long id { get; set; }
		public string repository_path { get; set; }
		public string version { get; set; }
		public string script_name { get; set; }
		public string text_of_script { get; set; }
		public string erroneous_part_of_script { get; set; }
		public string error_message { get; set; }
		public DateTime? entry_date { get; set; }
		public DateTime? modified_date { get; set; }
		public string entered_by { get; set; }
	}
    
    public partial class Feedback 
    {
		public long Id { get; set; }
		public long TalkId { get; set; }
		public string Summary { get; set; }
		public string Comments { get; set; }
		public DateTime EntryDate { get; set; }
	}
    
    public partial class Presentation 
    {
		public long Id { get; set; }
		public string Name { get; set; }
		public string Description { get; set; }
		public string User { get; set; }
		public DateTime DateCreated { get; set; }
	}
    
    public partial class Talk 
    {
		public long Id { get; set; }
		public long PresentationId { get; set; }
		public string Code { get; set; }
		public string Title { get; set; }
		public DateTime? StartDate { get; set; }
		public DateTime? EndDate { get; set; }
		public bool IsStarted { get; set; }
	}
}
